"""Belief-to-Action adapter: translate learned beliefs into behavioral changes."""
import json
import re
import time
from pathlib import Path
from .honcho.models import get_honcho_db, get_beliefs, belief_stage
from .evo_models import get_rules as get_agent_rules, rule_count, add_proposal, get_proposals, update_proposal_status
from metano.log import logger
from .paths import EVOLUTION_DIR, SUGGESTIONS_FILE, LOG_FILE, CONFIG_PATH as CONFIG_FILE

CLAUDE_MD = Path.home() / 'CLAUDE.md'
MEMORY_DIR = Path.home() / '.claude' / 'projects' / '-home-dk' / 'memory'
MEMORY_INDEX = MEMORY_DIR / 'MEMORY.md'
MARKER_START = '<!-- LEARNED-PREFS-START -->'
MARKER_END = '<!-- LEARNED-PREFS-END -->'

def _sanitize_markers(text: str) -> str:
    """Remove evolution marker strings from content to prevent marker injection.

    S5：LLM 生成的提案内容可能伪造结束标记（MARKER_END），注入前必须先移除，
    防止逃逸出受控的 CLAUDE.md 区间写入任意内容。
    """
    return text.replace(MARKER_START, '').replace(MARKER_END, '')

def _ensure_dirs():
    EVOLUTION_DIR.mkdir(parents=True, exist_ok=True)

def _log(action: str, details: dict):
    """Append to evolution audit log."""
    _ensure_dirs()
    entry = {'timestamp': time.time(), 'action': action, **details}
    with open(LOG_FILE, 'a') as f:
        f.write(json.dumps(entry, ensure_ascii=False) + '\n')

def beliefs_to_claude_md_injection(beliefs: list[dict]) -> str:
    """Generate the marked section content for CLAUDE.md from beliefs and agent_rules."""
    from .evo_models import get_rules as get_agent_rules
    lines = [MARKER_START, '# Learned Preferences (auto-generated by evolution)']
    by_category: dict[str, list[dict]] = {}
    for b in beliefs:
        cat = b.get('category', 'general')
        by_category.setdefault(cat, []).append(b)
    for cat, cat_beliefs in sorted(by_category.items()):
        lines.append(f'\n## {cat.title()}')
        for b in cat_beliefs:
            stage = belief_stage(b)
            # S5：清除信念内容中的标记字符串，防止伪造结束标记破坏 CLAUDE.md 结构
            safe_content = _sanitize_markers(b['content'])
            lines.append(f"- {safe_content} (confidence: {b['confidence']:.0%}, stage: {stage})")
    rules = get_agent_rules(active_only=True)
    if rules:
        lines.append('\n## Behavior Rules')
        for r in rules:
            eff = r.get('effectiveness', 0)
            applied = r.get('times_applied', 0)
            eff_str = f' (effectiveness: {eff:.0%}, applied: {applied}x)' if applied > 0 else ''
            safe_rule = _sanitize_markers(r['content'])
            lines.append(f"- {safe_rule}{eff_str}")
    lines.append(MARKER_END)
    return '\n'.join(lines)

def apply_beliefs_to_claude_md(dry_run: bool=True) -> dict:
    """Inject learned beliefs into CLAUDE.md within marked section.

    Only includes beliefs with confidence >= 0.7 and not contradicted.
    Preserves all content outside the markers.
    """
    conn = get_honcho_db()
    try:
        beliefs = get_beliefs(conn, 'default')
        eligible = [b for b in beliefs if b['confidence'] >= 0.7 and (not b.get('contradicted'))]
        if not eligible:
            return {'action': 'claude_md', 'status': 'skipped', 'reason': 'no eligible beliefs (confidence >= 0.7)'}
        injection = beliefs_to_claude_md_injection(eligible)
        if dry_run:
            return {'action': 'claude_md', 'status': 'dry_run', 'injection_preview': injection[:500], 'belief_count': len(eligible)}
        content = CLAUDE_MD.read_text() if CLAUDE_MD.exists() else ''
        if MARKER_START in content:
            start_idx = content.index(MARKER_START)
            end_idx = content.index(MARKER_END) + len(MARKER_END)
            new_content = content[:start_idx] + injection + content[end_idx:]
        else:
            new_content = content.rstrip() + '\n\n' + injection + '\n'
        CLAUDE_MD.write_text(new_content)
        _log('claude_md_inject', {'belief_count': len(eligible), 'categories': list(set((b['category'] for b in eligible)))})
        return {'action': 'claude_md', 'status': 'applied', 'belief_count': len(eligible)}
    finally:
        conn.close()

def beliefs_to_memory_file(beliefs: list[dict], category: str, dry_run: bool = True) -> dict | None:
    """Generate memory files from learned beliefs.

    Creates structured memory files in the memory directory for each category
    of learned beliefs. Only includes beliefs with confidence >= 0.6.

    S6：category 来自 LLM，必须按白名单正则 [a-z0-9_-]+ 消毒，非法则拒绝，
    防止 ``learned-../xxx`` 路径穿越写任意文件。
    S1：dry_run=True 时只返回预览，不真实写入记忆文件（自动 cron 不允许直接写盘，
    用户显式运行时才真实写入）。
    """
    if category == 'behavior_pattern':
        return None
    # S6：category 白名单消毒，非法字符直接拒绝（防止路径穿越）
    if not re.fullmatch(r'[a-z0-9_-]+', category or ''):
        logger.warning(f"memory_file: 非法 category {category!r}，已拒绝写入")
        return None
    eligible = [b for b in beliefs if b['category'] == category and b['confidence'] >= 0.6 and (not b.get('contradicted'))]
    if len(eligible) < 2:
        return None
    slug = f'learned-{category}'
    filepath = MEMORY_DIR / f'{slug}.md'
    lines = ['---', f'name: {slug}', f'description: Auto-generated from learned {category} beliefs', 'metadata:', '  type: feedback', '---', '']
    for b in eligible:
        stage = belief_stage(b)
        lines.append(f"- {_sanitize_markers(b['content'])} (confidence: {b['confidence']:.0%}, stage: {stage})")
    if dry_run:
        return {'action': 'memory_file', 'category': category, 'status': 'dry_run', 'file': str(filepath), 'belief_count': len(eligible)}
    filepath.write_text('\n'.join(lines))
    _add_to_memory_index(slug, f'Auto-learned {category} preferences')
    _log('memory_file_create', {'category': category, 'belief_count': len(eligible), 'file': str(filepath)})
    return {'action': 'memory_file', 'category': category, 'file': str(filepath), 'belief_count': len(eligible)}

def _add_to_memory_index(slug: str, description: str):
    """Add a pointer to the memory index file."""
    if not MEMORY_INDEX.exists():
        return
    content = MEMORY_INDEX.read_text()
    link = f'- [{slug}]({slug}.md)'
    if link in content:
        return
    MEMORY_INDEX.write_text(content.rstrip() + f'\n{link} — {description}\n')

def beliefs_to_behavior_improvements(beliefs: list[dict]) -> list[dict]:
    """Get behavior rules from evo_models (separate from Honcho user beliefs)."""
    agent_rules = get_agent_rules(kind='behavior')
    suggestions = []
    for r in agent_rules:
        # Skip low-confidence rules so they don't clutter the proposal queue.
        if r.get('confidence', 0.5) < 0.7:
            continue
        content = r['content']
        slug = content[:30].replace(' ', '-').replace('，', '').replace('。', '').replace('、', '')
        import re
        slug = re.sub('[^\\w-]', '', slug).lower()[:30]
        suggestions.append({'id': f"evo-{r['id']}", 'rule_id': r['id'], 'type': 'behavior_improvement', 'content': content, 'suggestion': content, 'slug': slug, 'effectiveness': r['effectiveness'], 'status': 'pending' if r.get('source') == 'correction_cluster' else 'applied', 'created_at': r['created_at']})
    return suggestions

def apply_behavior_improvement(suggestion_id: str) -> dict | None:
    """Apply an approved behavior_improvement by writing to Claude Code memory."""
    suggestions = load_suggestions()
    target = None
    for s in suggestions:
        if s['id'] == suggestion_id and s.get('type') == 'behavior_improvement':
            target = s
            break
    if not target:
        return None
    slug = target.get('slug', 'unknown-rule')
    filename = f'behavior-{slug}.md'
    filepath = MEMORY_DIR / filename
    content = f"---\nname: behavior-{slug}\ndescription: 自动检测的行为改进规则 — {target['content'][:60]}\nmetadata:\n  type: feedback\n---\n\n## 规则：{target['content']}\n\n**Why:** 用户已多次纠正此问题，进化系统自动检测并生成此规则\n\n**How to apply:** 每次涉及相关操作时必须遵守此规则，不要假设已满足，必须主动验证\n"
    filepath.write_text(content)
    _add_to_memory_index(f'behavior-{slug}', f"行为改进: {target['content'][:50]}")
    for s in suggestions:
        if s['id'] == suggestion_id:
            s['status'] = 'applied'
    SUGGESTIONS_FILE.write_text(json.dumps(suggestions, ensure_ascii=False, indent=2))
    _log('behavior_improvement_apply', {'suggestion_id': suggestion_id, 'file': str(filepath)})
    return {'status': 'applied', 'file': str(filepath), 'suggestion_id': suggestion_id}

def beliefs_to_setting_suggestions(beliefs: list[dict]) -> list[dict]:
    """Generate setting change suggestions from beliefs. Never auto-applied.

    Only creates proposals with concrete, actionable key=value changes.
    Vague preferences are skipped — they belong in CLAUDE.md/memory, not config.
    """
    suggestions = []
    for b in beliefs:
        if b['confidence'] < 0.8 or b.get('contradicted'):
            continue
        cat = b.get('category', '')
        content = b.get('content', '')
        if cat != 'preference':
            continue
        # Only create proposals for preferences that map to specific config keys
        lower = content.lower()
        if '中文' in lower or 'chinese' in lower or 'language=zh' in lower:
            suggestions.append({
                'id': f"sug-{b['id']}",
                'belief_id': b['id'],
                'type': 'setting_suggestion',
                'content': 'ui_language=zh-CN',
                'suggestion': 'Set UI language to Chinese (zh-CN)',
                'status': 'pending',
                'created_at': time.time(),
            })
        elif 'proxy' in lower or '代理' in lower:
            suggestions.append({
                'id': f"sug-proxy-{b['id']}",
                'belief_id': b['id'],
                'type': 'setting_suggestion',
                'content': 'proxy_enabled=true',
                'suggestion': 'Enable proxy configuration',
                'status': 'pending',
                'created_at': time.time(),
            })
    return suggestions

def save_suggestions(suggestions: list[dict]):
    """Save suggestions to evo.db proposals table (dedup by content)."""
    from .evo_models import add_proposal, get_proposals as _get_all
    existing_contents = {p['content'] for p in _get_all()}
    for s in suggestions:
        content = s.get('suggestion', s.get('content', ''))
        if content in existing_contents:
            continue
        ptype = s.get('type', 'behavior_improvement')
        if ptype == 'setting_suggestion':
            ptype = 'config_change'
        elif ptype == 'belief_promotion':
            ptype = 'rule_add'
        detail = s.get('content', '')
        source = s.get('type', 'evolution')
        add_proposal(ptype, content, detail=detail, source=source)
        existing_contents.add(content)

def execute_adaptation_cycle(dry_run: bool=True) -> dict:
    """Run the full belief-to-action adaptation cycle.

    Generates proposals from beliefs, behavior rules, and strategy patterns.
    Proposals are stored in evo.db proposals table and pending_suggestions.json.
    """
    conn = get_honcho_db()
    try:
        beliefs = get_beliefs(conn, 'default')
        active = [b for b in beliefs if not b.get('contradicted')]
        results = {'dry_run': dry_run, 'actions': [], 'proposals_created': 0}

        # 1. Inject beliefs into CLAUDE.md
        claude_md_result = apply_beliefs_to_claude_md(dry_run=dry_run)
        results['actions'].append(claude_md_result)

        # 2. Generate memory files from beliefs
        categories = set((b['category'] for b in active))
        for cat in categories:
            mem_result = beliefs_to_memory_file(active, cat, dry_run=dry_run)
            if mem_result:
                results['actions'].append(mem_result)

        # 3. Create proposals from setting suggestions
        from .evo_models import get_proposals as _get_proposals
        all_proposals = _get_proposals()
        existing_contents = {p['content'] for p in all_proposals}
        suggestions = beliefs_to_setting_suggestions(active)
        if suggestions and not dry_run:
            for s in suggestions:
                content = s.get('suggestion', s.get('content', ''))
                if content in existing_contents:
                    continue
                pid = add_proposal('config_change', content, s.get('content', ''), source='belief')
                if not pid:
                    continue
                existing_contents.add(content)
                results['proposals_created'] += 1
            results['actions'].append({'action': 'setting_suggestions', 'count': len(suggestions), 'status': 'pending_approval'})

        # 4. Create proposals from behavior improvements
        behavior_suggestions = beliefs_to_behavior_improvements(active)
        if behavior_suggestions and not dry_run:
            for s in behavior_suggestions:
                content = s.get('content', '')
                if content in existing_contents:
                    continue
                pid = add_proposal('behavior_improvement', content, source='behavior_rule')
                if not pid:
                    continue
                existing_contents.add(content)
                results['proposals_created'] += 1
            results['actions'].append({'action': 'behavior_improvements', 'count': len(behavior_suggestions), 'status': 'pending_approval'})

        # 5. Create proposals from strategy patterns
        try:
            from .strategy import detect_strategy_patterns
            strategy_patterns = detect_strategy_patterns()
            if strategy_patterns and not dry_run:
                for p in strategy_patterns:
                    if p.get('rule_suggestion') and p.get('confidence', 0) >= 0.8:
                        ptype = _classify_strategy(p)
                        pid = add_proposal(ptype, p.get('rule_suggestion', ''), json.dumps(p, ensure_ascii=False), source='strategy')
                        if not pid:
                            continue
                        results['proposals_created'] += 1
                results['actions'].append({'action': 'strategy_patterns', 'count': len(strategy_patterns), 'status': 'pending_approval'})
        except Exception:
            logger.exception("adaptation: strategy pattern detection failed")

        _log('adaptation_cycle', {'dry_run': dry_run, 'action_count': len(results['actions']), 'proposals_created': results['proposals_created']})

        # Notify user about pending proposals
        if results['proposals_created'] > 0:
            try:
                from .evolution_notify import notify_pending_proposals
                from .evo_models import get_proposals
                pending = get_proposals(status='pending')
                notify_pending_proposals(pending)
            except Exception:
                logger.exception("adaptation: notify failed")

        return results
    finally:
        conn.close()


def _classify_strategy(pattern: dict) -> str:
    """Classify a strategy pattern into a proposal type."""
    text = f"{pattern.get('rule_suggestion', '')} {pattern.get('action_type', '')}".lower()
    if any(kw in text for kw in ['config', 'parameter', 'threshold', 'timeout']):
        return 'config_change'
    if any(kw in text for kw in ['claude.md', 'claude_md', 'instruction']):
        return 'claude_md_inject'
    if any(kw in text for kw in ['rule', 'policy', 'constraint', 'block', 'deny']):
        return 'rule_add'
    return 'behavior_improvement'


# ── Proposal execution engine ──


def apply_proposal(proposal_id: int) -> dict:
    """Execute an approved proposal. Only runs if status is 'approved'.

    Dispatches to type-specific handlers. Updates proposal status to
    'applied' or 'failed' based on outcome.
    """
    from .evo_models import get_proposals, update_proposal_status
    proposals = get_proposals()
    target = next((p for p in proposals if p['id'] == proposal_id), None)
    if not target:
        return {'status': 'not_found'}
    if target['status'] != 'approved':
        return {'status': 'wrong_state', 'current_status': target['status']}

    ptype = target['proposal_type']
    content = target['content']
    detail = target.get('detail', '')

    # Record baseline metrics before applying
    try:
        from .evolution_eval import record_baseline
        record_baseline(proposal_id)
    except Exception:
        logger.exception()

    try:
        if ptype == 'behavior_improvement':
            result = _apply_behavior_improvement(content, detail)
        elif ptype == 'config_change':
            result = _apply_config_change(content, detail)
        elif ptype == 'rule_add':
            result = _apply_rule_add(content, detail)
        elif ptype == 'claude_md_inject':
            result = _apply_claude_md(content, detail)
        elif ptype == 'skill_improvement':
            result = _apply_skill_improvement(content, detail)
        elif ptype == 'new_skill_suggestion':
            result = _apply_new_skill(content, detail)
        else:
            result = {'status': 'unknown_type', 'type': ptype}

        outcome = result.get('status', 'failed')
        update_proposal_status(proposal_id, outcome if outcome in ('applied', 'failed') else 'applied',
                               json.dumps(result, ensure_ascii=False))
        _log('proposal_apply', {'proposal_id': proposal_id, 'type': ptype, 'outcome': outcome})
        return result
    except Exception:
        logger.exception()
        update_proposal_status(proposal_id, 'failed', 'execution error')
        return {'status': 'failed', 'type': ptype}


def _apply_behavior_improvement(content: str, detail: str) -> dict:
    """Add behavior rule to evo.db only (not memory files)."""
    from .evo_models import add_rule as add_evo_rule
    rule_id = add_evo_rule(kind='behavior', content=content, source='evolution_proposal')
    return {'status': 'applied', 'type': 'behavior_improvement', 'rule_id': rule_id}


def _apply_config_change(content: str, detail: str) -> dict:
    """Modify gateway_config.yaml based on proposal content.

    Parses the proposal to extract key/value changes and applies them.
    Only modifies existing keys — never adds new ones without user confirmation.
    """
    import yaml
    if not CONFIG_FILE.exists():
        return {'status': 'failed', 'reason': 'config file not found'}
    config = yaml.safe_load(CONFIG_FILE.read_text()) or {}
    # Try to parse "key=value" format from content
    changes = []
    for part in content.split(';'):
        if '=' in part:
            key, value = part.split('=', 1)
            key = key.strip()
            value = value.strip()
            # Only modify keys that already exist in config
            if key in config:
                old_value = config[key]
                config[key] = value
                changes.append({'key': key, 'old': old_value, 'new': value})
    if not changes:
        return {'status': 'failed', 'reason': 'no valid key=value changes found'}
    CONFIG_FILE.write_text(yaml.dump(config, allow_unicode=True, default_flow_style=False))
    return {'status': 'applied', 'type': 'config_change', 'changes': changes}


def _apply_rule_add(content: str, detail: str) -> dict:
    """Add agent rule to evo.db only (not memory files)."""
    from .evo_models import add_rule as add_evo_rule
    rule_id = add_evo_rule(kind='strategy', content=content, source='evolution_proposal')
    return {'status': 'applied', 'type': 'rule_add', 'rule_id': rule_id}


def _apply_skill_improvement(content: str, detail: str) -> dict:
    """Execute an approved skill_improvement proposal: add a references file
    under the target skill capturing the correction-derived lesson, plus a
    pointer in SKILL.md. Runs only after user approval (force path)."""
    try:
        from .skill_improvement import apply_skill_improvement
        return apply_skill_improvement(content, detail)
    except Exception:
        logger.exception("_apply_skill_improvement failed")
        return {'status': 'failed', 'type': 'skill_improvement'}


def _apply_new_skill(content: str, detail: str) -> dict:
    """Execute an approved new_skill_suggestion: actually CREATE the skill.

    The suggestion was raised because a correction had NO matching existing
    skill. On approval we create a minimal new skill derived from the
    correction: name = slugified correction, description = correction, content
    = a prompt template pointing at the correction. This closes the loop
    "discover missing capability → propose → approve → create".
    """
    try:
        import json as _json
        import re as _re
        from .skills.manager import SkillManager
        correction = content
        try:
            d = _json.loads(detail) if detail else {}
            if d.get('correction'):
                correction = d['correction']
        except Exception:
            pass
        # Derive a safe skill name from the correction (english/kebab slug).
        slug = _re.sub(r'[^a-zA-Z0-9]+', '-', correction)[:30].strip('-').lower() or 'new-skill'
        manager = SkillManager()
        skill_content = (
            f"# {slug}\n\n"
            f"> Auto-created from an approved suggestion.\n\n"
            f"## Task\n{correction}\n\n"
            f"Use this skill when the request matches the description below."
        )
        result = manager.create(
            name=slug,
            category='user',
            description=correction[:120],
            content=skill_content,
            version='1.0.0',
            author='evolution',
        )
        return {'status': 'applied', 'type': 'new_skill_suggestion', 'skill': slug, 'result': result}
    except Exception:
        logger.exception("_apply_new_skill failed")
        return {'status': 'failed', 'type': 'new_skill_suggestion'}


def _apply_claude_md(content: str, detail: str) -> dict:
    """Inject content into CLAUDE.md within the evolution markers.

    S5：注入前移除内容中的 MARKER_START/MARKER_END 标记字符串，防止伪造结束
    标记逃逸出受控区间，在 CLAUDE.md 里写入任意内容。
    """
    safe_content = _sanitize_markers(content).strip()
    existing = CLAUDE_MD.read_text() if CLAUDE_MD.exists() else ''
    if MARKER_START not in existing:
        existing = existing.rstrip() + '\n\n' + MARKER_START + '\n' + MARKER_END + '\n'
    start_idx = existing.index(MARKER_START)
    end_idx = existing.index(MARKER_END)
    injection = existing[start_idx + len(MARKER_START):end_idx].rstrip() + f'\n- {safe_content}'
    new_content = existing[:start_idx] + MARKER_START + injection + '\n' + existing[end_idx:]
    CLAUDE_MD.write_text(new_content)
    return {'status': 'applied', 'type': 'claude_md_inject', 'content': safe_content}


def apply_approved_proposals() -> dict:
    """Apply all approved proposals. Called by cron after approval window."""
    from .evo_models import get_proposals, update_proposal_status
    approved = get_proposals(status='approved')
    results = []
    for p in approved:
        result = apply_proposal(p['id'])
        results.append({'proposal_id': p['id'], 'type': p['proposal_type'], 'outcome': result.get('status')})
    _log('bulk_apply', {'applied': len([r for r in results if r['outcome'] == 'applied']),
                        'failed': len([r for r in results if r['outcome'] == 'failed'])})
    return {'total': len(approved), 'results': results}