"""X/Twitter search MCP tool.

Uses the xAI (Grok) API to search Twitter/X content.
Requires XAI_API_KEY environment variable.
"""
import json
import os
import urllib.request
import urllib.error
from pathlib import Path
from metano.log import logger
XAI_API_KEY = os.environ.get('XAI_API_KEY', '')
XAI_BASE_URL = 'https://api.x.ai/v1'

def search_x(query: str, limit: int=10) -> dict:
    """Search X/Twitter using xAI Grok API.

    WARNING: This does NOT call the real Twitter/X API.
    Results are LLM-generated by Grok and may be fabricated.
    Treat results as fictional suggestions, not real posts.
    """
    if not XAI_API_KEY:
        return {'error': 'XAI_API_KEY not set. Get one from https://console.x.ai and set: export XAI_API_KEY=your_key', 'query': query}
    payload = {'model': 'grok-3', 'messages': [{'role': 'system', 'content': f'Search X/Twitter for the latest posts about: {query}. Return the most relevant and recent posts as a JSON array with fields: author, text, date, engagement. Limit to {limit} results. If no results found, explain why.'}, {'role': 'user', 'content': query}], 'temperature': 0.1, 'max_tokens': 2000}
    headers = {'Content-Type': 'application/json', 'Authorization': f'Bearer {XAI_API_KEY}'}
    try:
        req = urllib.request.Request(f'{XAI_BASE_URL}/chat/completions', data=json.dumps(payload).encode(), headers=headers)
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read().decode())
            content = result['choices'][0]['message']['content']
            return {'query': query, 'results': content, 'model': 'grok-3'}
    except urllib.error.HTTPError as e:
        body = e.read().decode() if e.fp else ''
        return {'error': f'xAI API error {e.code}: {body[:200]}', 'query': query}
    except Exception as e:
        logger.exception()
        return {'error': str(e), 'query': query}